-- Snowflake-like DDL for TPC-H CUSTOMER
CREATE OR REPLACE TABLE {{TABLE_FQN}} (
  C_CUSTKEY BIGINT,
  C_NAME VARCHAR(25),
  C_ADDRESS VARCHAR(40),
  C_NATIONKEY INT,
  C_PHONE VARCHAR(15),
  C_ACCTBAL DOUBLE,
  C_MKTSEGMENT VARCHAR(10),
  C_COMMENT VARCHAR(117)
);