-- Spark SQL DDL for TPC-H CUSTOMER (Iceberg table)
CREATE TABLE {{TABLE_FQN}} (
  C_CUSTKEY BIGINT,
  C_NAME STRING,
  C_ADDRESS STRING,
  C_NATIONKEY INT,
  C_PHONE STRING,
  C_ACCTBAL DOUBLE,
  C_MKTSEGMENT STRING,
  C_COMMENT STRING
) USING iceberg;