-- Snowflake-like DDL for TPC-H ORDERS
CREATE OR REPLACE TABLE {{TABLE_FQN}} (
  O_ORDERKEY BIGINT,
  O_CUSTKEY BIGINT,
  O_ORDERSTATUS VARCHAR(1),
  O_TOTALPRICE DOUBLE,
  O_ORDERDATE DATE,
  O_ORDERPRIORITY VARCHAR(15),
  O_CLERK VARCHAR(15),
  O_SHIPPRIORITY INT,
  O_COMMENT VARCHAR(79)
);

