-- Spark SQL DDL for TPC-H ORDERS (Iceberg table)
CREATE TABLE {{TABLE_FQN}} (
  O_ORDERKEY BIGINT,
  O_CUSTKEY BIGINT,
  O_ORDERSTATUS STRING,
  O_TOTALPRICE DOUBLE,
  O_ORDERDATE DATE,
  O_ORDERPRIORITY STRING,
  O_CLERK STRING,
  O_SHIPPRIORITY INT,
  O_COMMENT STRING
) USING iceberg;

