-- Snowflake-like DDL for TPC-H PART
CREATE OR REPLACE TABLE {{TABLE_FQN}} (
  P_PARTKEY BIGINT,
  P_NAME VARCHAR(55),
  P_MFGR VARCHAR(25),
  P_BRAND VARCHAR(10),
  P_TYPE VARCHAR(25),
  P_SIZE INT,
  P_CONTAINER VARCHAR(10),
  P_RETAILPRICE DOUBLE,
  P_COMMENT VARCHAR(23)
);