-- Spark SQL DDL for TPC-H PARTSUPP (Iceberg table)
CREATE TABLE {{TABLE_FQN}} (
  PS_PARTKEY BIGINT,
  PS_SUPPKEY BIGINT,
  PS_AVAILQTY INT,
  PS_SUPPLYCOST DOUBLE,
  PS_COMMENT STRING
) USING iceberg;