-- Spark SQL DDL for TPC-H PART (Iceberg table)
CREATE TABLE {{TABLE_FQN}} (
  P_PARTKEY BIGINT,
  P_NAME STRING,
  P_MFGR STRING,
  P_BRAND STRING,
  P_TYPE STRING,
  P_SIZE INT,
  P_CONTAINER STRING,
  P_RETAILPRICE DOUBLE,
  P_COMMENT STRING
) USING iceberg;