-- Spark SQL DDL for TPC-H SUPPLIER (Iceberg table)
CREATE TABLE {{TABLE_FQN}} (
  S_SUPPKEY BIGINT,
  S_NAME STRING,
  S_ADDRESS STRING,
  S_NATIONKEY INT,
  S_PHONE STRING,
  S_ACCTBAL DOUBLE,
  S_COMMENT STRING
) USING iceberg;